const char* shortdesc[141] = {
 NULL,
 /* 1 */ "You're at end of road again.\n",
 /* 2 */ "You're at hill in road.\n",
 /* 3 */ "You're inside building.\n",
 /* 4 */ "You're in valley.\n",
 /* 5 */ "You're in forest.\n",
 /* 6 */ "You're in forest.\n",
 /* 7 */ "You're at slit in streambed.\n",
 /* 8 */ "You're outside grate.\n",
 /* 9 */ "You're below the grate.\n",
 /* 10 */ "You're in cobble crawl.\n",
 /* 11 */ "You're in debris room.\n",
 NULL,
 /* 13 */ "You're in bird chamber.\n",
 /* 14 */ "You're at top of small pit.\n",
 /* 15 */ "You're in Hall of Mists.\n",
 NULL,
 /* 17 */ "You're on east bank of fissure.\n",
 /* 18 */ "You're in nugget of gold room.\n",
 /* 19 */ "You're in Hall of Mt King\n",
 NULL,
 NULL,
 NULL,
 /* 23 */ "You're at west end of Twopit Room.\n",
 /* 24 */ "You're in east pit.\n",
 /* 25 */ "You're in west pit.\n",
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 /* 33 */ "You're at \"Y2\".\n",
 NULL,
 /* 35 */ "You're at window on pit.\n",
 /* 36 */ "You're in dirty passage.\n",
 NULL,
 NULL,
 /* 39 */ "You're in dusty rock room.\n",
 NULL,
 /* 41 */ "You're at west end of Hall of Mists.\n",
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 /* 57 */ "You're at brink of pit.\n",
 NULL,
 NULL,
 /* 60 */ "You're at east end of long hall.\n",
 /* 61 */ "You're at west end of long hall.\n",
 NULL,
 NULL,
 /* 64 */ "You're at complex junction.\n",
 NULL,
 /* 66 */ "You're in Swiss Cheese Room.\n",
 /* 67 */ "You're at east end of Twopit Room.\n",
 /* 68 */ "You're in Slab Room.\n",
 NULL,
 NULL,
 /* 71 */ "You're at junction of three secret canyons.\n",
 NULL,
 NULL,
 /* 74 */ "You're in secret e/w canyon above tight canyon.\n",
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 NULL,
 /* 88 */ "You're in narrow corridor.\n",
 NULL,
 NULL,
 /* 91 */ "You're at steep incline above large room.\n",
 /* 92 */ "You're in Giant Room.\n",
 NULL,
 NULL,
 /* 95 */ "You're in cavern with waterfall.\n",
 /* 96 */ "You're in Soft Room.\n",
 /* 97 */ "You're in Oriental Room.\n",
 /* 98 */ "You're in misty cavern.\n",
 /* 99 */ "You're in alcove.\n",
 /* 100 */ "You're in Plover Room.\n",
 /* 101 */ "You're in dark-room.\n",
 /* 102 */ "You're in arched hall.\n",
 /* 103 */ "You're in Shell Room.\n",
 NULL,
 NULL,
 /* 106 */ "You're in anteroom.\n",
 NULL,
 /* 108 */ "You're at Witt's End.\n",
 /* 109 */ "You're in Mirror Canyon.\n",
 /* 110 */ "You're at window on pit.\n",
 /* 111 */ "You're at top of stalactite.\n",
 NULL,
 /* 113 */ "You're at reservoir.\n",
 NULL,
 /* 115 */ "You're at ne end.\n",
 /* 116 */ "You're at sw end.\n",
 /* 117 */ "You're on sw side of chasm.\n",
 /* 118 */ "You're in sloping corridor.\n",
 NULL,
 NULL,
 NULL,
 /* 122 */ "You're on ne side of chasm.\n",
 /* 123 */ "You're in corridor.\n",
 /* 124 */ "You're at fork in path.\n",
 /* 125 */ "You're at junction with warm walls.\n",
 /* 126 */ "You're at breath-taking view.\n",
 /* 127 */ "You're in Chamber of Boulders.\n",
 /* 128 */ "You're in limestone passage.\n",
 /* 129 */ "You're in front of Barren Room.\n",
 /* 130 */ "You're in Barren Room.\n"
};
